var annotated =
[
    [ "sglib", null, [
      [ "alignment", null, [
        [ "algorithms", null, [
          [ "SmithWaterman", "classsglib_1_1alignment_1_1algorithms_1_1_smith_waterman.html", "classsglib_1_1alignment_1_1algorithms_1_1_smith_waterman" ]
        ] ],
        [ "scoring", null, [
          [ "SubstitutionMatrix", "classsglib_1_1alignment_1_1scoring_1_1_substitution_matrix.html", "classsglib_1_1alignment_1_1scoring_1_1_substitution_matrix" ]
        ] ]
      ] ],
      [ "utilities", null, [
        [ "matrices", null, [
          [ "matrix", "classsglib_1_1utilities_1_1matrices_1_1matrix.html", "classsglib_1_1utilities_1_1matrices_1_1matrix" ]
        ] ]
      ] ],
      [ "basic_nullbuf", "classsglib_1_1basic__nullbuf.html", "classsglib_1_1basic__nullbuf" ],
      [ "basic_onullstream", "classsglib_1_1basic__onullstream.html", "classsglib_1_1basic__onullstream" ]
    ] ],
    [ "std", null, [
      [ "hash< KmerCount >", "structstd_1_1hash_3_01_kmer_count_01_4.html", "structstd_1_1hash_3_01_kmer_count_01_4" ],
      [ "hash< KmerIDX >", "structstd_1_1hash_3_01_kmer_i_d_x_01_4.html", "structstd_1_1hash_3_01_kmer_i_d_x_01_4" ],
      [ "hash< MinPosIDX >", "structstd_1_1hash_3_01_min_pos_i_d_x_01_4.html", "structstd_1_1hash_3_01_min_pos_i_d_x_01_4" ],
      [ "hash< ReadMapping >", "structstd_1_1hash_3_01_read_mapping_01_4.html", "structstd_1_1hash_3_01_read_mapping_01_4" ],
      [ "hash< LongReadMapping >", "structstd_1_1hash_3_01_long_read_mapping_01_4.html", "structstd_1_1hash_3_01_long_read_mapping_01_4" ]
    ] ],
    [ "AffineGapScoreModel", "class_affine_gap_score_model.html", "class_affine_gap_score_model" ],
    [ "Backbone", "class_backbone.html", "class_backbone" ],
    [ "BufferedLRSequenceGetter", "class_buffered_l_r_sequence_getter.html", "class_buffered_l_r_sequence_getter" ],
    [ "BufferedPairedSequenceGetter", "class_buffered_paired_sequence_getter.html", "class_buffered_paired_sequence_getter" ],
    [ "BufferedTagKmerizer", "class_buffered_tag_kmerizer.html", "class_buffered_tag_kmerizer" ],
    [ "ContigBlockFactory", "class_contig_block_factory.html", "class_contig_block_factory" ],
    [ "ContigLink", "class_contig_link.html", "class_contig_link" ],
    [ "ContigLinkFactory", "class_contig_link_factory.html", "class_contig_link_factory" ],
    [ "Counter", "struct_counter.html", "struct_counter" ],
    [ "FastaReader", "class_fasta_reader.html", "class_fasta_reader" ],
    [ "FastaRecord", "struct_fasta_record.html", "struct_fasta_record" ],
    [ "FastqReader", "class_fastq_reader.html", "class_fastq_reader" ],
    [ "FastqRecord", "struct_fastq_record.html", "struct_fastq_record" ],
    [ "FastxReaderParams", "struct_fastx_reader_params.html", "struct_fastx_reader_params" ],
    [ "FilterSetParams", "struct_filter_set_params.html", "struct_filter_set_params" ],
    [ "Flow", "class_flow.html", "class_flow" ],
    [ "FlowFollower", "class_flow_follower.html", "class_flow_follower" ],
    [ "GraphEditor", "class_graph_editor.html", "class_graph_editor" ],
    [ "GraphNodeReader", "class_graph_node_reader.html", "class_graph_node_reader" ],
    [ "GraphNodeReaderParams", "struct_graph_node_reader_params.html", "struct_graph_node_reader_params" ],
    [ "graphPosition", "structgraph_position.html", "structgraph_position" ],
    [ "graphStrandPos", "structgraph_strand_pos.html", "structgraph_strand_pos" ],
    [ "KmerCompressionIndex", "class_kmer_compression_index.html", "class_kmer_compression_index" ],
    [ "KmerCount", "struct_kmer_count.html", "struct_kmer_count" ],
    [ "KmerCountFactory", "class_kmer_count_factory.html", "class_kmer_count_factory" ],
    [ "KmerCountFactoryParams", "struct_kmer_count_factory_params.html", "struct_kmer_count_factory_params" ],
    [ "KMerFactory", "class_k_mer_factory.html", "class_k_mer_factory" ],
    [ "KmerIDX", "struct_kmer_i_d_x.html", "struct_kmer_i_d_x" ],
    [ "kmerIDXFactory", "classkmer_i_d_x_factory.html", "classkmer_i_d_x_factory" ],
    [ "KMerIDXFactoryParams", "struct_k_mer_i_d_x_factory_params.html", "struct_k_mer_i_d_x_factory_params" ],
    [ "KmerMapCounter", "class_kmer_map_counter.html", "class_kmer_map_counter" ],
    [ "KmerMapCreator", "class_kmer_map_creator.html", "class_kmer_map_creator" ],
    [ "KmerVectorCreator", "class_kmer_vector_creator.html", "class_kmer_vector_creator" ],
    [ "Link", "class_link.html", "class_link" ],
    [ "LinkageDiGraph", "class_linkage_di_graph.html", "class_linkage_di_graph" ],
    [ "LinkageUntangler", "class_linkage_untangler.html", "class_linkage_untangler" ],
    [ "LinkedReadData", "struct_linked_read_data.html", "struct_linked_read_data" ],
    [ "LinkedReadMapper", "class_linked_read_mapper.html", "class_linked_read_mapper" ],
    [ "LinkedReadsDatastore", "class_linked_reads_datastore.html", "class_linked_reads_datastore" ],
    [ "LogEntry", "class_log_entry.html", "class_log_entry" ],
    [ "LongReadMapper", "class_long_read_mapper.html", "class_long_read_mapper" ],
    [ "LongReadMapping", "struct_long_read_mapping.html", "struct_long_read_mapping" ],
    [ "LongReadsDatastore", "class_long_reads_datastore.html", "class_long_reads_datastore" ],
    [ "MappingThread", "class_mapping_thread.html", "class_mapping_thread" ],
    [ "MappingThreader", "class_mapping_threader.html", "class_mapping_threader" ],
    [ "MinPosIDX", "class_min_pos_i_d_x.html", "class_min_pos_i_d_x" ],
    [ "Node", "class_node.html", "class_node" ],
    [ "NodeMapper", "class_node_mapper.html", "class_node_mapper" ],
    [ "NodeMapping", "class_node_mapping.html", "class_node_mapping" ],
    [ "nodeVisitor", "structnode_visitor.html", "structnode_visitor" ],
    [ "PairedReadConnectivityDetail", "class_paired_read_connectivity_detail.html", "class_paired_read_connectivity_detail" ],
    [ "PairedReadData", "struct_paired_read_data.html", "struct_paired_read_data" ],
    [ "PairedReadLinker", "class_paired_read_linker.html", "class_paired_read_linker" ],
    [ "PairedReadMapper", "class_paired_read_mapper.html", "class_paired_read_mapper" ],
    [ "PairedReadsDatastore", "class_paired_reads_datastore.html", "class_paired_reads_datastore" ],
    [ "PathExplorer", "class_path_explorer.html", "class_path_explorer" ],
    [ "PathsDatastore", "class_paths_datastore.html", "class_paths_datastore" ],
    [ "ReaderStats", "struct_reader_stats.html", "struct_reader_stats" ],
    [ "ReadMapping", "class_read_mapping.html", "class_read_mapping" ],
    [ "ReadPosSize", "struct_read_pos_size.html", "struct_read_pos_size" ],
    [ "Scaffolder", "class_scaffolder.html", "class_scaffolder" ],
    [ "SequenceGraph", "class_sequence_graph.html", "class_sequence_graph" ],
    [ "SequenceGraphJournal", "class_sequence_graph_journal.html", null ],
    [ "SequenceGraphPath", "class_sequence_graph_path.html", "class_sequence_graph_path" ],
    [ "SequenceSubGraph", "class_sequence_sub_graph.html", "class_sequence_sub_graph" ],
    [ "SingleReadMapper", "class_single_read_mapper.html", "class_single_read_mapper" ],
    [ "SkipMerFactory", "class_skip_mer_factory.html", "class_skip_mer_factory" ],
    [ "SkipMerIDXFactory", "class_skip_mer_i_d_x_factory.html", "class_skip_mer_i_d_x_factory" ],
    [ "SkipMerIndex", "class_skip_mer_index.html", "class_skip_mer_index" ],
    [ "SMR", "class_s_m_r.html", "class_s_m_r" ],
    [ "SMRParams", "struct_s_m_r_params.html", "struct_s_m_r_params" ],
    [ "StrandedMinimiserSketchFactory", "class_stranded_minimiser_sketch_factory.html", "class_stranded_minimiser_sketch_factory" ],
    [ "StreamKmerFactory", "class_stream_kmer_factory.html", "class_stream_kmer_factory" ],
    [ "StringKMerFactory", "class_string_k_mer_factory.html", "class_string_k_mer_factory" ],
    [ "TagWalker", "class_tag_walker.html", "class_tag_walker" ],
    [ "UncoveredKmerCounter", "class_uncovered_kmer_counter.html", "class_uncovered_kmer_counter" ],
    [ "uniqueKmerIndex", "classunique_kmer_index.html", "classunique_kmer_index" ],
    [ "UniqueKmerIndex", "class_unique_kmer_index.html", "class_unique_kmer_index" ],
    [ "Untangler", "class_untangler.html", "class_untangler" ],
    [ "WorkSpace", "class_work_space.html", "class_work_space" ]
];