var hierarchy =
[
    [ "ContigBlockFactory< FileRecord >::accumulator< T, T2 >", "struct_contig_block_factory_1_1accumulator.html", null ],
    [ "ContigLinkFactory< FileRecord >::accumulator< T, T2 >", "struct_contig_link_factory_1_1accumulator.html", null ],
    [ "AffineGapScoreModel< T >", "class_affine_gap_score_model.html", null ],
    [ "Backbone", "class_backbone.html", null ],
    [ "basic_streambuf", null, [
      [ "sglib::basic_nullbuf< cT, traits >", "classsglib_1_1basic__nullbuf.html", null ]
    ] ],
    [ "ContigBlockFactory< FileRecord >::Block", "struct_contig_block_factory_1_1_block.html", null ],
    [ "ContigLinkFactory< FileRecord >::Block", "struct_contig_link_factory_1_1_block.html", null ],
    [ "BufferedLRSequenceGetter", "class_buffered_l_r_sequence_getter.html", null ],
    [ "BufferedPairedSequenceGetter", "class_buffered_paired_sequence_getter.html", null ],
    [ "BufferedTagKmerizer", "class_buffered_tag_kmerizer.html", null ],
    [ "ContigBlockFactory< FileRecord >::Block::byContig", "struct_contig_block_factory_1_1_block_1_1by_contig.html", null ],
    [ "SingleReadMapper::MatchOffset::byContigOffsetPos", "struct_single_read_mapper_1_1_match_offset_1_1by_contig_offset_pos.html", null ],
    [ "SingleReadMapper::MatchOffset::byContigRead", "struct_single_read_mapper_1_1_match_offset_1_1by_contig_read.html", null ],
    [ "ContigBlockFactory< FileRecord >::Match::byContigRef", "struct_contig_block_factory_1_1_match_1_1by_contig_ref.html", null ],
    [ "ContigBlockFactory< FileRecord >::Block::byCount", "struct_contig_block_factory_1_1_block_1_1by_count.html", null ],
    [ "ContigLink::byCount", "struct_contig_link_1_1by_count.html", null ],
    [ "ContigLinkFactory< FileRecord >::Match::byCtgOffset", "struct_contig_link_factory_1_1_match_1_1by_ctg_offset.html", null ],
    [ "KmerIDX::byCtgPos", "struct_kmer_i_d_x_1_1by_ctg_pos.html", null ],
    [ "SingleReadMapper::MatchOffset::byOffset", "struct_single_read_mapper_1_1_match_offset_1_1by_offset.html", null ],
    [ "ContigBlockFactory< FileRecord >::Block::byQuery", "struct_contig_block_factory_1_1_block_1_1by_query.html", null ],
    [ "SingleReadMapper::MatchOffset::byReadContig", "struct_single_read_mapper_1_1_match_offset_1_1by_read_contig.html", null ],
    [ "ContigBlockFactory< FileRecord >::Match::byReadPos", "struct_contig_block_factory_1_1_match_1_1by_read_pos.html", null ],
    [ "ContigLinkFactory< FileRecord >::Block::byReadPos", "struct_contig_link_factory_1_1_block_1_1by_read_pos.html", null ],
    [ "SingleReadMapper::MatchOffset::byReadPos", "struct_single_read_mapper_1_1_match_offset_1_1by_read_pos.html", null ],
    [ "ContigBlockFactory< FileRecord >::Block::byRefPos", "struct_contig_block_factory_1_1_block_1_1by_ref_pos.html", null ],
    [ "ContigLink", "class_contig_link.html", null ],
    [ "Counter", "struct_counter.html", null ],
    [ "FastaReader< FileRecord >", "class_fasta_reader.html", null ],
    [ "FastaRecord", "struct_fasta_record.html", null ],
    [ "FastqReader< FileRecord >", "class_fastq_reader.html", null ],
    [ "FastqRecord", "struct_fastq_record.html", null ],
    [ "FastxReaderParams", "struct_fastx_reader_params.html", null ],
    [ "FilterSetParams", "struct_filter_set_params.html", null ],
    [ "Flow", "class_flow.html", null ],
    [ "FlowFollower", "class_flow_follower.html", null ],
    [ "GraphEditor", "class_graph_editor.html", null ],
    [ "GraphNodeReader< FileRecord >", "class_graph_node_reader.html", null ],
    [ "GraphNodeReaderParams", "struct_graph_node_reader_params.html", null ],
    [ "graphPosition", "structgraph_position.html", null ],
    [ "graphStrandPos", "structgraph_strand_pos.html", null ],
    [ "std::hash< KmerCount >", "structstd_1_1hash_3_01_kmer_count_01_4.html", null ],
    [ "std::hash< KmerIDX >", "structstd_1_1hash_3_01_kmer_i_d_x_01_4.html", null ],
    [ "std::hash< LongReadMapping >", "structstd_1_1hash_3_01_long_read_mapping_01_4.html", null ],
    [ "std::hash< MinPosIDX >", "structstd_1_1hash_3_01_min_pos_i_d_x_01_4.html", null ],
    [ "std::hash< ReadMapping >", "structstd_1_1hash_3_01_read_mapping_01_4.html", null ],
    [ "std::ios_base", null, [
      [ "std::basic_ios< Char >", null, [
        [ "std::basic_ostream< Char >", null, [
          [ "sglib::basic_onullstream< cT, traits >", "classsglib_1_1basic__onullstream.html", null ]
        ] ]
      ] ]
    ] ],
    [ "KmerCompressionIndex", "class_kmer_compression_index.html", null ],
    [ "KmerCount", "struct_kmer_count.html", null ],
    [ "KmerCountFactoryParams", "struct_kmer_count_factory_params.html", null ],
    [ "KMerFactory", "class_k_mer_factory.html", [
      [ "BufferedTagKmerizer::StreamKmerFactory", "class_buffered_tag_kmerizer_1_1_stream_kmer_factory.html", null ],
      [ "ContigBlockFactory< FileRecord >", "class_contig_block_factory.html", null ],
      [ "ContigLinkFactory< FileRecord >", "class_contig_link_factory.html", null ],
      [ "KmerCountFactory< FileRecord >", "class_kmer_count_factory.html", null ],
      [ "kmerIDXFactory< FileRecord >", "classkmer_i_d_x_factory.html", null ],
      [ "KmerMapCounter", "class_kmer_map_counter.html", null ],
      [ "KmerMapCreator", "class_kmer_map_creator.html", null ],
      [ "KmerVectorCreator", "class_kmer_vector_creator.html", null ],
      [ "LinkedReadMapper::StreamKmerFactory", "class_linked_read_mapper_1_1_stream_kmer_factory.html", null ],
      [ "StrandedMinimiserSketchFactory", "class_stranded_minimiser_sketch_factory.html", null ],
      [ "StreamKmerFactory", "class_stream_kmer_factory.html", null ],
      [ "StringKMerFactory", "class_string_k_mer_factory.html", null ],
      [ "UncoveredKmerCounter", "class_uncovered_kmer_counter.html", null ]
    ] ],
    [ "KmerIDX", "struct_kmer_i_d_x.html", null ],
    [ "KMerIDXFactoryParams", "struct_k_mer_i_d_x_factory_params.html", null ],
    [ "Link", "class_link.html", null ],
    [ "LinkageDiGraph", "class_linkage_di_graph.html", null ],
    [ "LinkageUntangler", "class_linkage_untangler.html", null ],
    [ "LinkedReadData", "struct_linked_read_data.html", null ],
    [ "LinkedReadMapper", "class_linked_read_mapper.html", null ],
    [ "LinkedReadsDatastore", "class_linked_reads_datastore.html", null ],
    [ "LogEntry", "class_log_entry.html", null ],
    [ "LongReadMapper", "class_long_read_mapper.html", null ],
    [ "LongReadMapping", "struct_long_read_mapping.html", null ],
    [ "LongReadsDatastore", "class_long_reads_datastore.html", null ],
    [ "MappingThread", "class_mapping_thread.html", null ],
    [ "MappingThreader", "class_mapping_threader.html", null ],
    [ "ContigBlockFactory< FileRecord >::Match", "struct_contig_block_factory_1_1_match.html", null ],
    [ "ContigLinkFactory< FileRecord >::Match", "struct_contig_link_factory_1_1_match.html", null ],
    [ "SingleReadMapper::MatchOffset", "struct_single_read_mapper_1_1_match_offset.html", null ],
    [ "sglib::utilities::matrices::matrix< T >", "classsglib_1_1utilities_1_1matrices_1_1matrix.html", [
      [ "sglib::alignment::scoring::SubstitutionMatrix< T >", "classsglib_1_1alignment_1_1scoring_1_1_substitution_matrix.html", null ]
    ] ],
    [ "sglib::utilities::matrices::matrix< trace_t >", "classsglib_1_1utilities_1_1matrices_1_1matrix.html", null ],
    [ "MinPosIDX", "class_min_pos_i_d_x.html", null ],
    [ "Node", "class_node.html", null ],
    [ "NodeMapper", "class_node_mapper.html", null ],
    [ "NodeMapping", "class_node_mapping.html", null ],
    [ "nodeVisitor", "structnode_visitor.html", null ],
    [ "PairedReadConnectivityDetail", "class_paired_read_connectivity_detail.html", null ],
    [ "PairedReadData", "struct_paired_read_data.html", null ],
    [ "PairedReadLinker", "class_paired_read_linker.html", null ],
    [ "PairedReadMapper", "class_paired_read_mapper.html", null ],
    [ "PairedReadsDatastore", "class_paired_reads_datastore.html", null ],
    [ "PathExplorer", "class_path_explorer.html", null ],
    [ "PathsDatastore", "class_paths_datastore.html", null ],
    [ "ReaderStats", "struct_reader_stats.html", null ],
    [ "ReadMapping", "class_read_mapping.html", null ],
    [ "ReadPosSize", "struct_read_pos_size.html", null ],
    [ "Scaffolder", "class_scaffolder.html", null ],
    [ "SequenceGraph", "class_sequence_graph.html", null ],
    [ "SequenceGraphJournal", "class_sequence_graph_journal.html", null ],
    [ "SequenceGraphPath", "class_sequence_graph_path.html", null ],
    [ "SequenceSubGraph", "class_sequence_sub_graph.html", null ],
    [ "SingleReadMapper", "class_single_read_mapper.html", null ],
    [ "SkipMerFactory", "class_skip_mer_factory.html", [
      [ "SkipMerIDXFactory< FileRecord >", "class_skip_mer_i_d_x_factory.html", null ]
    ] ],
    [ "SkipMerIndex", "class_skip_mer_index.html", null ],
    [ "sglib::alignment::algorithms::SmithWaterman< T >", "classsglib_1_1alignment_1_1algorithms_1_1_smith_waterman.html", null ],
    [ "SMR< RecordType, RecordFactory, FileReader, FileRecord, ReaderParamStruct, FactoryParamStruct >", "class_s_m_r.html", null ],
    [ "SMRParams", "struct_s_m_r_params.html", null ],
    [ "BufferedTagKmerizer::tag_kmers_t", "struct_buffered_tag_kmerizer_1_1tag__kmers__t.html", null ],
    [ "TagWalker", "class_tag_walker.html", null ],
    [ "uniqueKmerIndex", "classunique_kmer_index.html", null ],
    [ "UniqueKmerIndex", "class_unique_kmer_index.html", null ],
    [ "Untangler", "class_untangler.html", null ],
    [ "Counter::value_type", "struct_counter_1_1value__type.html", null ],
    [ "WorkSpace", "class_work_space.html", null ]
];