var searchData=
[
  ['subgraph_20extraction_20tool',['Subgraph extraction tool',['../md__home_travis_build_ljyanesm_sg_src_gfa-extract.html',1,'']]],
  ['seq_2dsorter_20output_20files',['seq-sorter output files',['../md__home_travis_build_ljyanesm_sg_src_seq-sorter.html',1,'']]],
  ['sglib',['sglib',['../md__home_travis_build_ljyanesm_sg_src_sglib__r_e_a_d_m_e.html',1,'']]],
  ['scaffolder',['Scaffolder',['../class_scaffolder.html',1,'Scaffolder'],['../class_scaffolder.html#ac668583c8150b1d0d0874b2e27be53ba',1,'Scaffolder::Scaffolder()']]],
  ['score',['score',['../struct_long_read_mapping.html#a72d98cf2f9c8fb88fde20eaafe48275a',1,'LongReadMapping']]],
  ['sequencegraph',['SequenceGraph',['../class_sequence_graph.html',1,'']]],
  ['sequencegraphjournal',['SequenceGraphJournal',['../class_sequence_graph_journal.html',1,'']]],
  ['sequencegraphpath',['SequenceGraphPath',['../class_sequence_graph_path.html',1,'']]],
  ['sequencesubgraph',['SequenceSubGraph',['../class_sequence_sub_graph.html',1,'']]],
  ['singlereadmapper',['SingleReadMapper',['../class_single_read_mapper.html',1,'']]],
  ['skate_5ffrom_5fnode',['skate_from_node',['../class_flow_follower.html#af9e9717707072f32d09c0f350ed0e168',1,'FlowFollower']]],
  ['skipmerfactory',['SkipMerFactory',['../class_skip_mer_factory.html',1,'']]],
  ['skipmeridxfactory',['SkipMerIDXFactory',['../class_skip_mer_i_d_x_factory.html',1,'']]],
  ['skipmerindex',['SkipMerIndex',['../class_skip_mer_index.html',1,'']]],
  ['smithwaterman',['SmithWaterman',['../classsglib_1_1alignment_1_1algorithms_1_1_smith_waterman.html',1,'sglib::alignment::algorithms']]],
  ['smr',['SMR',['../class_s_m_r.html',1,'']]],
  ['smrparams',['SMRParams',['../struct_s_m_r_params.html',1,'']]],
  ['solve_5fbubbly_5fpath',['solve_bubbly_path',['../class_untangler.html#a85c068929740a3c37eacc1558c0f9e66',1,'Untangler']]],
  ['solve_5fbubbly_5fpath_5f2',['solve_bubbly_path_2',['../class_untangler.html#a89273e74b00b26fc5d18c26340fc1225',1,'Untangler']]],
  ['solve_5fbubbly_5fpaths',['solve_bubbly_paths',['../class_untangler.html#ae2506fd72b64a11eb91413ef29054a3d',1,'Untangler']]],
  ['strandedminimisersketchfactory',['StrandedMinimiserSketchFactory',['../class_stranded_minimiser_sketch_factory.html',1,'']]],
  ['streamkmerfactory',['StreamKmerFactory',['../class_buffered_tag_kmerizer_1_1_stream_kmer_factory.html',1,'BufferedTagKmerizer']]],
  ['streamkmerfactory',['StreamKmerFactory',['../class_linked_read_mapper_1_1_stream_kmer_factory.html',1,'LinkedReadMapper']]],
  ['streamkmerfactory',['StreamKmerFactory',['../class_stream_kmer_factory.html',1,'']]],
  ['stringkmerfactory',['StringKMerFactory',['../class_string_k_mer_factory.html',1,'']]],
  ['substitutionmatrix',['SubstitutionMatrix',['../classsglib_1_1alignment_1_1scoring_1_1_substitution_matrix.html',1,'sglib::alignment::scoring']]],
  ['summarystatistics',['summaryStatistics',['../class_s_m_r.html#ad3ad59b16b4226c91fa04bea9bf20550',1,'SMR']]]
];
